package com.miguelcordoba.LibraryService.dto;

import io.micrometer.common.lang.Nullable;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.time.LocalDate;
import java.util.Set;

public record AuthorDTO(
        Long id, //id is JPA-autogenerated, so we won´t validate it

        @NotBlank(message = "First name cannot be blank")
        String name,

        @NotBlank(message = "Last name cannot be blank")
        LocalDate dateOfBirth,

        @Nullable
        Set<NestedBookDTO> books // This allows creating an author without books
) {}
