### profiles(?)
######### meta
info:
  app:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    packaging: '@project.packaging@'
    description: '@project.description@'
    version: '@project.version@'
    properties:
      java:
        version: '@java.version@'

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  sql:
    init:
      mode: never

server:
  error:
    include-message: always
